### ISSUE TITLE
USER STORY: Navigation with sidebar

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4-Cityfur#11]
As a **user** I can **always access the navigation** so that **I can get so every feature of the side easily.**

## Acceptance Criteria

- The sidebar is visible on larger screens.

- On mobile view with mid to small screens, the sidebar can be opened by a burger menu.

- Sidebar can easily be closed on mobile view.

## Tasks

- [x] Add responsive behavior

- [x] Add show and hide functionality

- [x] Add burger menu for mobile view.
