### ISSUE TITLE
USER STORY: Create new guest profile

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4-Cityfur#12]
As an **employee** I can **create a new guest profile** so that **the guest can be checked-in**

## Acceptance Criteria

- Have an easy to use form to fill out.

- Be able to upload an image of the new guest.

- If no image is available, a placeholder image should be used automatically.

## Tasks

- [x] Create add-guest view and template.

- [x] Create forms file with forms logic.

- [x] Add functionality to check for duplicate first name and name addon.

- [x] Implement into app navigation
