### ISSUE TITLE
USER STORY: Guest allergies

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4-Cityfur#15]
As a **user** I can **see in the profile and the preview if a guest has allergies** so that **allergies don't go overseen**

## Acceptance Criteria

- A symbol in the profile preview in the list is shown.

- In the profile detail view, I can see all information about a possible allergy.

## Tasks

- [ ] Add allergies to model.

- [ ] Add allergies to profile preview

- [ ] Add allergies to detailed profile.
