### ISSUE TITLE
USER STORY: Dynamic Alerts for Food, Medication and Pickup

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4-Cityfur#16]
As an **employee** I can **at every time see important information about food, medication or pickup** so that **no important information gets overlooked.**

## Acceptance Criteria

- Symbol for Food, Medication and Pickup has to be shown in guest list.

- When clicking on a profile in list, times for food and medications, as well as name of other pickup person should be shown.

- If no important information are stored, nothing should show up.

## Tasks

- [x] Add food icon and time

- [x] Add medication icon and functionality

- [x] Add pickup icon and functionality

- [x] Add field to save pickup information on check-in
