### ISSUE TITLE
USER STORY: Write Reposts

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4-Cityfur#17]
As an **user** I can **write report entries for each day** so that **important things that happend are documented.**

## Acceptance Criteria

- Select the date and see related reports

- Write reports for selected date

- Mention guests in report

## Tasks

- [x] Create reports model

- [x] Create form for writing a report

- [x] Copy and adapt date selector from guests list

- [x] Create listing for reports on selected day

- [x] Create edit function for report

- [x] Create delete function for report
