### ISSUE TITLE
USER STORY: Guests list

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4-Cityfur#3]
As an **employee** I can **see a list of guests** so that **I know who is present at the current day**

## Acceptance Criteria

- A list with all guests marked as present

- Each guest with name, name addon, gender and picture

- Overview with important facts like medication, food and other issues

## Tasks

- [x] Create guests app

- [x] Create guests model, view & template

- [x] All settings in django app

- [x] Display list with present guests filtered by date
