### ISSUE TITLE
USER STORY: Guest check-in

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4-Cityfur#5]
As an **employee**, I can **check-in new guest dogs** so that **they appear in the guest list**

## Acceptance Criteria

- Easy to find check-in feature on guest list.

- Load page to find and select the guest to check in.

- Open confirmation modal with option to adjust the check-in time.

- Reload of guest list with new guest in it.

## Tasks

- [x] Add check-in button to guest list.

- [x] Create page so search all not checked-in guests.
 
- [x] Create confirmation modal.

- [x] Search database by name for guest to check-in.

- [x] Add list of search result to select the guest to check in.
