### ISSUE TITLE
USER STORY: User authentication

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4-Cityfur#6]
As a **user** I can **login** so that **I can use the app as my role allowes**

## Acceptance Criteria

- User can login with username and password

- Users can create new account

- No logged out user can use the app

## Tasks

- [x] Create login system and page

- [x] Create user table in database

- [x] Create page for registration
