### ISSUE TITLE
USER STORY: Filter guests list by gender

### ISSUE THREAD

**Issue by DennisSchenkel** [DennisSchenkel/PP4-Cityfur#7]
As an **employee**, I can **filter the list of guest dogs by gender** so that **I can have an overview of the guest dogs of each gender**

## Acceptance Criteria

- Enable filter to select male, female and all.

- User can easily switch between filters.

## Tasks

- [x] Create filter selector with HTML and CSS.

- [x] Link HTML selector elements to functionality.

- [x] Create filter functionality with JS
